# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║  WARNING — SANDBOX ONLY.  DO NOT COPY TO PRODUCTION.                       ║
# ║                                                                             ║
# ║  This file intentionally uses settings that are UNSAFE for production:     ║
# ║    • purge_soft_delete_on_destroy = true  (KV secrets permanently deleted) ║
# ║    • recover_soft_deleted_key_vaults = false  (no recovery on destroy)     ║
# ║    • prevent_deletion_if_contains_resources = false  (no guard on RG)      ║
# ║                                                                             ║
# ║  These settings exist so the sandbox environment can be cleanly destroyed  ║
# ║  with `terraform destroy`.  Production stacks must use the opposite values ║
# ║  and are generated by `dataforge generate --env prod`.                     ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

terraform {
  required_version = ">= 1.7"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 4.0"
    }
    # databricks provider added in Phase 2 when we provision Unity Catalog / clusters
  }
}

provider "azurerm" {
  resource_provider_registrations = "none"
  subscription_id                 = var.subscription_id
  tenant_id                       = var.tenant_id

  features {
    key_vault {
      purge_soft_delete_on_destroy    = true   # sandbox: allow clean destroy
      recover_soft_deleted_key_vaults = false
    }
    resource_group {
      prevent_deletion_if_contains_resources = false
    }
  }
}
