# ============================================================
# RBAC Role Assignments — generated by DataForge RBAC matrix
# ============================================================

# ADF managed identity → ADLS (reads source data)
resource "azurerm_role_assignment" "adf__adls__storage_blob_data_reader" {
  # ADF managed identity needs Storage Blob Data Reader on ADLS for read
  principal_id         = azurerm_data_factory.main.identity[0].principal_id
  role_definition_id   = "/subscriptions/${var.subscription_id}/providers/Microsoft.Authorization/roleDefinitions/2a2b9908-6ea1-4ae2-8e65-a410df84e7d1"
  scope                = azurerm_storage_account.main.id
}

# ADF managed identity → Databricks (triggers notebooks/jobs)
resource "azurerm_role_assignment" "adf__databricks__contributor" {
  # ADF managed identity needs Contributor on Databricks to trigger jobs
  principal_id         = azurerm_data_factory.main.identity[0].principal_id
  role_definition_id   = "/subscriptions/${var.subscription_id}/providers/Microsoft.Authorization/roleDefinitions/b24988ac-6180-42a0-ab88-20f7382dd24c"
  scope                = azurerm_databricks_workspace.main.id
}

# ADF managed identity → Key Vault (reads linked-service secrets)
resource "azurerm_role_assignment" "adf__kv__key_vault_secrets_user" {
  # ADF managed identity needs Key Vault Secrets User on Key Vault
  principal_id         = azurerm_data_factory.main.identity[0].principal_id
  role_definition_id   = "/subscriptions/${var.subscription_id}/providers/Microsoft.Authorization/roleDefinitions/4633458b-17de-408a-b874-0445c86b69e6"
  scope                = azurerm_key_vault.main.id
}

# Databricks cluster → ADLS / Key Vault RBAC
# NOTE: storage_account_identity is only populated when CMK is enabled for
# managed services — it is empty on a standard workspace. Cluster-level ADLS
# access requires Unity Catalog credential vending or a service principal;
# add those in Phase 2 after Unity Catalog is provisioned.

# Current user → Key Vault admin (so you can add secrets manually during testing)
resource "azurerm_role_assignment" "current_user__kv__admin" {
  principal_id         = data.azurerm_client_config.current.object_id
  role_definition_id   = "/subscriptions/${var.subscription_id}/providers/Microsoft.Authorization/roleDefinitions/b86a8fe4-44ce-4948-aee5-eccb2c155cd7"
  scope                = azurerm_key_vault.main.id
}
